steps:
  # 1. Cloner le Backend (Méthode sécurisée)
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://github.com/reloke/reloke-back.git backend

  # 2. Cloner le Frontend (Méthode sécurisée)
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://github.com/reloke/reloke-front.git frontend

  # 3. Builder l'image Docker unique
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/reloke-monolith', '.']

  # 4. Pousser l'image vers le registre Google
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/reloke-monolith']

  # 5. Déployer sur Cloud Run (Région Paris)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'reloke-api',
        '--image', 'gcr.io/$PROJECT_ID/reloke-monolith',
        '--region', 'europe-west9',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/reloke-monolith'

options:
  logging: CLOUD_LOGGING_ONLY